# Generated by Django 4.2.2 on 2023-07-02 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_remove_ticket_tags_alter_ticket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='participants',
        ),
        migrations.AddField(
            model_name='ticket',
            name='participants',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
