# Generated by Django 4.2.2 on 2023-07-02 22:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('mainapp', '0004_remove_ticket_participants_ticket_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
