# Generated by Django 4.2.2 on 2023-07-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_ticket_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Resolved', 'Resolved')], default='In progress', max_length=12),
        ),
    ]
