# Generated by Django 4.2.2 on 2023-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('In progress', 'Active'), ('Resolved', 'Complete')], default='In progress', max_length=12),
        ),
    ]
