# Generated by Django 4.2.2 on 2023-07-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CMP', 'Complete')], default='ACT', max_length=10),
        ),
    ]
