# Generated by Django 4.2.2 on 2023-07-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_message_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ticket_id',
        ),
    ]
